// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Authenticate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListLiveCategories():Promise<Array<models.Category>>;

export function ListShowCategories():Promise<Array<models.Category>>;

export function ListVodCategories():Promise<Array<models.Category>>;
