// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Authenticate'](arg1, arg2, arg3, arg4);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function ListLiveCategories() {
  return window['go']['main']['App']['ListLiveCategories']();
}

export function ListShowCategories() {
  return window['go']['main']['App']['ListShowCategories']();
}

export function ListVodCategories() {
  return window['go']['main']['App']['ListVodCategories']();
}
