// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Authenticate'](arg1, arg2, arg3, arg4);
}

export function GetLiveStreamUrl(arg1) {
  return window['go']['main']['App']['GetLiveStreamUrl'](arg1);
}

export function GetVodDetails(arg1) {
  return window['go']['main']['App']['GetVodDetails'](arg1);
}

export function GetVodUrl(arg1) {
  return window['go']['main']['App']['GetVodUrl'](arg1);
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function ListLiveCategories() {
  return window['go']['main']['App']['ListLiveCategories']();
}

export function ListLiveStreams(arg1) {
  return window['go']['main']['App']['ListLiveStreams'](arg1);
}

export function ListShowCategories() {
  return window['go']['main']['App']['ListShowCategories']();
}

export function ListVodCategories() {
  return window['go']['main']['App']['ListVodCategories']();
}

export function ListVods(arg1) {
  return window['go']['main']['App']['ListVods'](arg1);
}
